language: objective-c
osx_image: xcode8.1
script:
  - set -o pipefail
  - xcodebuild test -scheme Kanagata -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.0'
notifications:
  email: true