language: objective-c
osx_image: xcode9
before_install:
  - brew update
  - brew install swiftlint
script:
  - set -o pipefail
  - pod lib lint --allow-warnings
  - swiftlint
  - xcodebuild test -scheme Kanagata-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=9.0' | xcpretty -c
  - xcodebuild test -scheme Kanagata-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty -c
  - xcodebuild test -scheme Kanagata-macOS -destination 'platform=OS X' | xcpretty -c
  - xcodebuild test -scheme Kanagata-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
